controllers:
    resource: ../src/Application/Controller/
    type: annotation

labelControllers:
    resource: ../src/Application/TSG/Scheme/Label/Application/Controller/
    type: annotation

kernel:
    resource: ../src/Application/Kernel.php
    type: annotation
